version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smtmax-postgres
    restart: always
    environment:
      POSTGRES_USER: rokki
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: smtmax_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smtmax -d smtmax_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
